### ISSUE TITLE
Syntax highlighting for records

### ISSUE THREAD

**Issue by dumikaiya** [Alejandro-FA/vscode-theme-dartpad#6]
Currently the named variable of records are just plain white, I'm not sure if this is a feature or because Dart 3 is new?
for example:
```dart
void main() {
  ({int a, String b}) multipleVar = (a:15, b:'');
  print(multipleVar .a);
}
```
In this case, a and b are just plain white.

P.S: My default theme for Flutter, I like it

**Comment by Alejandro-FA** [comment]
Hi, thank you very much for your contribution :), I am glad that you like the theme for Flutter development.

If records are not colored properly, it is probably because I either overlooked this syntax when testing the theme or because it is indeed a new feature.

As you can see in the commit history of the repository, it has been inactive for a while. Currently I don't have much time to dedicate to side projects, and improving this theme is low on my list of priorities. However, **Pull Requests are welcome**, and I would be willing to merge them if not much work is involved. Otherwise, I will keep this issue as my no. 1 priority for when I have time to dedicate to the theme.

If you have never modified a Visual Studio Code theme, I suggest taking a look at the documentation: https://code.visualstudio.com/docs/getstarted/themes. You can even modify the theme to your liking with a few steps (without needing to contribute the change to this extension): https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by dumikaiya** [comment]
Unfortunately I have never done a PR so I don't know how, I will try to research and look at how to modify themes, thanks for the links :) closing the issue for now.
